var str="";
console.log(str);
str += "零基础学";
console.log(str);
str += "javascript<br>";
console.log(str);
document.write(str);
var number1 = 1 < 6;
document.write(number1);
var number2 = 7 > 10;
document.write('<br>');
document.write(number2);
document.write('<br>');
var number3 = 10 <= 10;
document.write(number3);
document.write('<br>');
var number4 = 3 >= 6;
document.write(number4);
document.write('<br>');
var number5 = "18" == 18;
document.write(number5);
document.write('<br>');
var number6 = "19" === 19;
document.write(number6);

var number7 = "17"!=17;
document.write(number7);
var number8 = "17"!==17;
document.write(number8);
document.write('<br>');
var a = 10;
document.write(a==10);
document.write('<br>');
var age = 25;
document.write("age变量的值为:" + age);
document.write('<p>');
document.write("age>20: ");
document.write(age>20);
document.write('<br>');
document.write("age<20: ");
document.write(age<20);
document.write('<br>');
document.write("age==20: ");
document.write(age==20);
document.write('<br>');
document.write("ac"<"bc");
document.write('<br>');
document.write("abcd">"abc");
document.write('<br>');
document.write("abc"=="abc");
